steps:
  - name: hashicorp/terraform:$_TERRAFORM_VERSION
    args:
      - init
  - name: hashicorp/terraform:$_TERRAFORM_VERSION
    args:
      - validate
  - name: hashicorp/terraform:$_TERRAFORM_VERSION
    args:
      - plan
      - '-out'
      - 'tf.plan'
substitutions:
  _TERRAFORM_VERSION: 1.0.5