steps:
  - name: hashicorp/terraform:$_TERRAFORM_VERSION
    args:
      - init
  - name: hashicorp/terraform:$_TERRAFORM_VERSION
    args:
      - plan
      - '-out'
      - 'tf.plan'
  - name: hashicorp/terraform:$_TERRAFORM_VERSION
    args:
      - apply
      - '-auto-approve'
      - 'tf.plan'
substitutions:
  _TERRAFORM_VERSION: 1.3.9