steps:
  - name: hashicorp/terraform:light
    args:
      - init
  - name: hashicorp/terraform:light
    args:
      - plan
      - '-out'
      - 'tf.plan'
  - name: hashicorp/terraform:light
    args:
      - apply
      - '-auto-approve'
      - 'tf.plan'